spring:
  application:
    name: infrastructure

  datasource:
    url: jdbc:mysql://localhost:3306/project_movie
    username: master
    password: password
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always