USE app_db;

-- MOVIE 테이블 생성
CREATE TABLE IF NOT EXISTS MOVIE (
    id CHAR(36) PRIMARY KEY COMMENT '고유 식별자',
    title VARCHAR(255) NOT NULL COMMENT '타이틀',
    release_date DATE NOT NULL COMMENT '개봉일',
    thumbnail_url VARCHAR(512) COMMENT '썸네일 URL',
    runtime_minutes INT NOT NULL COMMENT '러닝 타임 (분)',
    genre VARCHAR(100) NOT NULL COMMENT '장르',
    rating VARCHAR(50) NOT NULL COMMENT '영상물 등급'
);

-- SCREEN 테이블 생성
CREATE TABLE IF NOT EXISTS SCREEN (
    id CHAR(36) PRIMARY KEY COMMENT '고유 식별자',
    name VARCHAR(255) NOT NULL COMMENT '상영관 이름',
    `row` INT NOT NULL COMMENT '좌석 행 수',
    `column` INT NOT NULL COMMENT '좌석 열 수'
);

-- SHOWTIME 테이블 생성
CREATE TABLE IF NOT EXISTS SHOWTIME (
    id CHAR(36) PRIMARY KEY COMMENT '고유 식별자',
    movie_id CHAR(36) NOT NULL COMMENT '영화 ID',
    screen_id CHAR(36) NOT NULL COMMENT '상영관 ID',
    start_time DATETIME NOT NULL COMMENT '시작 시간',
    FOREIGN KEY (movie_id) REFERENCES MOVIE(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (screen_id) REFERENCES SCREEN(id) ON DELETE CASCADE ON UPDATE CASCADE
);
