services:
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_USERNAME: master
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: project-movie
    volumes:
      - ./database:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      retries: 5
