services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - db_data:/var/lib/mysql
#      - ./docs/data/ddl_no_index.sql:/docker-entrypoint-initdb.d/ddl_no_index.sql:ro
      - ./docs/data/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
      - ./docs/data/dummy_data.sql:/docker-entrypoint-initdb.d/dummy_data.sql:ro
      - ./docs/data/dummy_data_movie.sql:/docker-entrypoint-initdb.d/dummy_data_movie.sql:ro
      - ./docs/data/dummy_data_screening.sql:/docker-entrypoint-initdb.d/dummy_data_screening.sql:ro
    command: [
      "--character-set-server=utf8mb4",           # MySQL 서버 기본 문자 집합을 utf8mb4로 설정
      "--collation-server=utf8mb4_general_ci",    # MySQL 서버 기본 정렬 규칙을 utf8mb4_general_ci로 설정
      "--default-time-zone=Asia/Seoul"              # MySQL 서버 기본 타임존을 KST(+09:00)로 설정
    ]
    networks:
      - cinema_network
#  app:
#    build:
#      context: .
#    container_name: cinema_app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3307/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
#    depends_on:
#      - db
#      - redis
#    networks:
#      - cinema_network
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "no" ]
#    command: [ "redis-server", "--appendonly", "yes" ]  # AOF(Append-Only File) 활성화

volumes:
  db_data:

networks:
  cinema_network:

