services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
#      - ./ddl_no_index.sql:/docker-entrypoint-initdb.d/ddl_no_index.sql:ro
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
      - ./dummy_data.sql:/docker-entrypoint-initdb.d/dummy_data.sql:ro
      - ./dummy_data_movie.sql:/docker-entrypoint-initdb.d/dummy_data_movie.sql:ro
      - ./dummy_data_screening.sql:/docker-entrypoint-initdb.d/dummy_data_screening.sql:ro
    networks:
      - cinema_network
#  app:
#    build:
#      context: .
#    container_name: cinema_app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3307/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
#    depends_on:
#      - db
#      - redis
#    networks:
#      - cinema_network
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "no" ]
#    command: [ "redis-server", "--appendonly", "yes" ]  # AOF(Append-Only File) 활성화

volumes:
  db_data:

networks:
  cinema_network:

