version: '3'
services:
  # 서비스 명
  mysql:
    # 사용할 이미지
    image: mysql:8.0
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: mysql2
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "3306:3306"
    # 환경 변수 설정
    environment:
      MYSQL_ROOT_PASSWORD: root1234!!
      TZ: Asia/Seoul
    # 명렬어 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    # 볼륨 설정
    volumes:
      - ./data/mysql/:/var/lib/mysql8


  # redis-server.yml
  #version: '3.7'
  #services:
   # redis:
    #  image: redis:alpine
     # command: redis-server --port 6379
     # container_name: redis_boot
     # hostname: redis_boot
     # labels:
      #  - "name=redis"
      #  - "mode=standalone"
      #ports:
       # - 6379:6379
