spring:
  datasource:
    url: jdbc:mysql://localhost:3305/hanghae99
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6378
  sql:
    init:
      data-locations: classpath:data.sql
      platform: mysql
      mode: always

logging:
  level:
    org.springframework.cache: trace