spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379

# (선택) 서버 포트 변경
# server:
#   port: 8080
