spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/redis-movie?useSSL=false&allowPublicKeyRetrieval=true
    username: hongs
    password: local1234

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    placeholder-replacement: false
    locations: classpath:db/migration

logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql:
              info

redis:
  host: localhost
  port: 6380


management:
  endpoints:
    web:
      exposure:
        include: "*"