spring:
  application:
    name: app-api

  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost:3307/redis_prac_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver


  cache:
    type: redis
    redis:
      host: localhost # Redis 컨테이너 호스트
      port: 6379      # Redis 포트