version: '3.8' #Docker Compose 버전

services:
  mysql:
    image: mysql:8.0 # 사용할 MySQL 이미지 버전
    container_name: mysql-container # 컨테이너 이름
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movies
      MYSQL_USER: admin
      MYSQL_PASSWORD: gkdgo
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


