version: '3'
services:
  redis-movie:
    image: mysql:9.1.0
    container_name: cinema-mysql
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=redis-movie
      - MYSQL_USER=hongs
      - MYSQL_PASSWORD=local1234
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci