spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8080
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc: TRACE
    com.example.movieapi: debug
    com.example.movieinfra: debug
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      platform: h2
      encoding: utf-8
---
spring:
  config:
    activate:
      on-profile: local-index
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_db
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema-mysql-base.sql
        - classpath:sql/schema-mysql-index.sql
      data-locations:
        - classpath:sql/data-mysql.sql
---
spring:
  config:
    activate:
      on-profile: local-caffeine
  cache:
    type: caffeine
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_db
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema-mysql-base.sql
        - classpath:sql/schema-mysql-index.sql
      data-locations:
        - classpath:sql/data-mysql.sql
---
spring:
  config:
    activate:
      on-profile: local-redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_db
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema-mysql-base.sql
        - classpath:sql/schema-mysql-index.sql
      data-locations:
        - classpath:sql/data-mysql.sql
---
spring:
  config:
    activate:
      on-profile: prod
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:3306/movie_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema-mysql.sql
        - classpath:sql/schema-mysql-index.sql
      data-locations: classpath:sql/data-mysql.sql