spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cinema?useSSL=false&allowPublicKeyRetrieval=true
    username: cinema_user
    password: cinema_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # Hibernate가 DDL을 생성하지 않도록 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
