spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_database
    username: dev_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true # JPA 엔티티 초기화 이후 data.sql을 실행
    properties:
      hibernate.format_sql: true

  sql:
    init:
      mode: always # 항상 data.sql 실행

logging:
  level:
    org.hibernate.sql: DEBUG                   # SQL 쿼리 로깅
    org.hibernate.orm.jdbc.bind: TRACE         # SQL 바인딩 파라미터 로깅
    org.hibernate.type.descriptor.sql: TRACE   # SQL 파라미터 값 로깅
    org.springframework.transaction.interceptor: DEBUG  # 트랜잭션 정보
